name: Test SchemaCrawler (Local) Action

on:
  workflow_dispatch:

jobs:
  hello:
    name: Test SchemaCrawler (Local) Action
    runs-on: ubuntu-latest

    steps:
    - id: install-schemacrawler
      name: Install SchemaCrawler on the GitHub Actions runner
      uses: schemacrawler/SchemaCrawler-Local-Action@v17.11.4

    - id: schemacrawler-report
      name: Create SchemaCrawler report
      env:
        SDKMAN_DIR: ${{ github.workspace }}/.sdkman
      shell: bash
      run: |
        # Run SchemaCrawler against a test database
        source "$SDKMAN_DIR/bin/sdkman-init.sh"
        schemacrawler.sh \
            --server=sqlite \
            --database=$SDKMAN_DIR/candidates/schemacrawler/17.11.4/sc.db \
            --info-level=standard \
            --command script \
            --tables "Authors|Books|BookAuthors" \
            --script-language python \
            --script /scripts/mermaid.py \
            --output-file mermaid-er.mmd \
            --log-level CONFIG

    - id: display-report
      name: Wrap Mermaid diagram in Markdown and display as job output
      run: |
        # Create enclosing Markdown file with Mermaid code block
        echo '```mermaid' > mermaid-diagram.md
        cat mermaid-er.mmd >> mermaid-diagram.md
        echo '```' >> mermaid-diagram.md
        # Display the wrapped content in workflow output
        cat mermaid-diagram.md >> $GITHUB_STEP_SUMMARY
